server:
  port: 1011

# springCloud-hystrix
spring:
  cloud:
    hystrix:
      command:
        default:
          execution:
            isolation:
              thread:
                timeoutInMilliseconds: 100  # 设置 Hystrix 命令的超时时间
          circuitBreaker:
            requestVolumeThreshold: 1  # 触发熔断器的最小请求数
            sleepWindowInMilliseconds: 5000  # 熔断器打开后进入半开状态的时间窗口
            errorThresholdPercentage: 50  # 触发熔断器的错误百分比
      thread:
        pool:
          default:
            coreSize: 10  # Hystrix 线程池的核心线程数
            maxSize: 10  # Hystrix 线程池的最大线程数
            queueSizeRejectionThreshold: 5  # Hystrix 线程池的队列大小拒绝阈值

      # 配置 Hystrix Dashboard 端点
      hystrix:
        stream:
          enabled: true
          # 默认情况下 Hystrix 的 Metrics Stream 端点是 /actuator/hystr

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
